### ISSUE TITLE
Uncaught exception - load.c(393) : Invalid module : run.n

### ISSUE THREAD

**Issue by ghost** [blackberry/NME#1]
I followed the instructions in the readme to use the dev version of nme however, whenever I run nme I receive the message: 

Uncaught exception - load.c(393) : Invalid module : run.n

I'm running OSX 10.7 (Lion). The output from haxelib list is: 

actuate: [1.52]
format: [3.0]
hxcpp: 2.10.3 [3.0.0]
nme: 3.5.5 [dev:NME]
svg: 1.04 [1.06]
swf: 1.17 [1.20]
xfl: [1.04]

NME is the relative path to where I cloned the git repo. Any suggestions?

**Comment by jgranick** [comment]
Try using a full path, such as ~/Development/Haxe/NME, or where you have it installed :)

**Comment by ghost** [comment]
I tried that but same error. I thought path was wrong but if I change run.n to blah.n in that directory I get the following message: 

Library nme version 3.5.5 does not have a run script

Which proves that the path listed by haxelib list is correct. 

It must be something within run.n which is causing nme to think it's an invalid module.

**Comment by ghost** [comment]
OK fixed it. My fault, the version of neko I had installed was 1.8.2. Solution: 
- Download latest version from http://nekovm.org/download
- Overwrite contents of /usr/lib/neko with latest version

**Comment by thomasuster** [comment]
Windows neko path was C:\Motion-Twin\neko.
